@startuml

cloud "Internet" {
[Sigfox]
[Anglo MDM]
[Google analytics]
}

package "Anglo Intranet" {

package "Anglo Azure Cloud" {
[Anglo APM]
database "MSSQL"
[RTLS] -> [MSSQL]
[RTLS] -down-> [Anglo APM] : Monitoring
}
package "Anglo Site Infrastructure" {
BLE_Beacon -down-> BLE_Gateway : BLE
BLE_Reader -down-> BLE_Gateway : BLE
BLE_Beacon -left-> BLE_Reader : "BLE    "
[RFID Component] -down-> [RTLS] : MQTT
BLE_Gateway -down-> [RTLS] : MQTT
WLDC_RFID_Reader -down-> [RFID Component] : LLRP over Ethernet
WLDC_Handheld_Device -down-> [RTLS] : HTTPS over Wifi
WLDC_Handheld_Device -up-> [Anglo MDM] : Wifi
WLDC_Handheld_Device -up-> [Google analytics] : Wifi
}
}


cloud "Internet" {
[Sigfox] -up-> [RTLS] : HTTPS
}

Sigfox_Device -up-> Sigfox : SigfoxNetwork

@enduml