@startuml

title "Mpact Architecture"

skinparam interface {
  backgroundColor Grey
  borderColor black
}

skinparam component {
  BackgroundColor white
}

skinparam database {
  BackgroundColor white
}


package "Mpact Network" {
package "Mpact Teraco" {
    package "Mpact Database Server" {
        database "Mpact Traxsense Database"
    }
    package "Mpact Application Server" {
        [MQTT Broker] <-up-> [Event Bridge] : MQTT (QoS 2)
        [Event Bridge] <-up-> [Mpact Traxsense Database] : Event Data
        [Traxsense] <-up-> [Mpact Traxsense Database] : Reports, Data
        [BI] <-up-> [Mpact Traxsense Database]
        [NGINX Load balancer] <-up-> [Traxsense] : HTTP, \nWebSockets
        [NGINX Load balancer] <-up-> [BI] : HTTP
        [NGINX Load balancer] <-up-> [MQTT Broker] : MQTT
    }


        circle "Mpact User"
        circle "Mpact Browser"
        circle "Mpact Handheld"
        [Mpact User] <-up-> [Mpact Browser]
        [Mpact User] <-up-> [Mpact Handheld]
        [Mpact Handheld] <-up-> [NGINX Load balancer] : HTTPS
        [Mpact Browser] <-up-> [NGINX Load balancer] : HTTPS
}
    package "Mpact Site" {

        circle "Mpact RFID Reader"
        [Mpact RFID Reader] <--> [Mpact Acquisition Service]
        [Mpact Acquisition Service] <--> [NGINX Load balancer] : MQTT
    }
}

package "Client Site Network" {
        User <-up-> Browser
        User <-up-> Handheld
        Handheld <-up-> [NGINX Load balancer] : HTTPS whitelisted IP
        Browser <-up-> [NGINX Load balancer] : HTTPS whitelisted IP
        circle "RFID Reader"
        package "Client Site Server" {
             database "SQL Express DB"
             [RFID Reader] <--> [Client Acquisition Service]
             [Client Acquisition Service] <--> [NGINX Load balancer] : MQTT whitelisted IP
             [Client Acquisition Service] <--> [SQL Express DB]
        }
    }

circle "VPN User"
circle "VPN Browser"
circle "VPN Handheld"

[VPN User] <-up-> [VPN Browser]
[VPN User] <-up-> [VPN Handheld]

[VPN Handheld] <-up-> [NGINX Load balancer] : HTTPS via VPN
[VPN Browser] <-up-> [NGINX Load balancer] : HTTPS via VPN



@enduml